export const ACTIONS = {
  RESET_STATE: "RESET_STATE",
  HANDLE_ITEM_PRESS: "HANDLE_ITEM_PRESS",
  ENTER_AMOUNTS: "ENTER_AMOUNTS",
  CALCULATE_AMOUNTS: "CALCULATE_AMOUNTS",
  HANDLE_SUBMIT: "HANDLE_SUBMIT",
  CANCEL: "CANCEL",
};

export const RECIPE_VIEW = {
  DEFAULT: "DEFAULT",
  PROCESSED: "PROCESSED",
};

export const POPUP_VIEW = {
  HIDDEN: "HIDDEN",
  FIRST_VIEW: "FIRST_VIEW",
  VALID_RECIPE_RECIPE_SELECTED: "VALID_RECIPE_RECIPE_SELECTED",
  ENTER_AMOUNTS: "ENTER_AMOUNTS",
  INVALID_RECIPE_VALID_RECIPE_SELECTED:
      "INVALID_RECIPE_VALID_RECIPE_SELECTED",
  INVALID_RECIPE_VALID_INGREDIENT_SELECTED:
      "INVALID_RECIPE_VALID_INGREDIENT_SELECTED",
  INVALID_RECIPE_INVALID_RECIPE_SELECTED:
      "INVALID_RECIPE_INVALID_RECIPE_SELECTED",
  INVALID_RECIPE_INVALID_INGREDIENT_SELECTED:
      "INVALID_RECIPE_INVALID_INGREDIENT_SELECTED",
};

export const TOTAL = {
  FLOUR: "FLOUR",
  LIQUID: "LIQUID",
  RECIPE: "RECIPE",
};

export const INPUT_IDS = {
  BATCH: "BATCH",
  UNIT: "UNIT",
};

export const TYPES = {
  MISSING_INGREDIENT_IN_PARENT: 'MISSING_INGREDIENT_IN_PARENT',
  TOTAL_FLOUR_NOT_100: 'TOTAL_FLOUR_NOT_100',
  NEGATIVE_STEP_PERCENTAGE: 'NEGATIVE_STEP_PERCENTAGE',
  MISSING_INGREDIENTS_IN_CHILD: 'MISSING_INGREDIENTS_IN_CHILD',
};
